pair_group: main_strong_6
directed_pairs:
- pair_index: 1
  pair_id: p01_vehicles1_to_vehicles2
  source_task: vehicles1
  target_task: vehicles2
  pair_group: main_strong_6
- pair_index: 1
  pair_id: p01_vehicles2_to_vehicles1
  source_task: vehicles2
  target_task: vehicles1
  pair_group: main_strong_6
- pair_index: 2
  pair_id: p02_aquatic_mammals_to_fish
  source_task: aquatic_mammals
  target_task: fish
  pair_group: main_strong_6
- pair_index: 2
  pair_id: p02_fish_to_aquatic_mammals
  source_task: fish
  target_task: aquatic_mammals
  pair_group: main_strong_6
- pair_index: 3
  pair_id: p03_flowers_to_trees
  source_task: flowers
  target_task: trees
  pair_group: main_strong_6
- pair_index: 3
  pair_id: p03_trees_to_flowers
  source_task: trees
  target_task: flowers
  pair_group: main_strong_6
- pair_index: 4
  pair_id: p04_insects_to_non_insect_invertebrates
  source_task: insects
  target_task: non_insect_invertebrates
  pair_group: main_strong_6
- pair_index: 4
  pair_id: p04_non_insect_invertebrates_to_insects
  source_task: non_insect_invertebrates
  target_task: insects
  pair_group: main_strong_6
- pair_index: 5
  pair_id: p05_small_mammals_to_medium_sized_mammals
  source_task: small_mammals
  target_task: medium_sized_mammals
  pair_group: main_strong_6
- pair_index: 5
  pair_id: p05_medium_sized_mammals_to_small_mammals
  source_task: medium_sized_mammals
  target_task: small_mammals
  pair_group: main_strong_6
- pair_index: 6
  pair_id: p06_large_carnivores_to_large_omnivores_herbivores
  source_task: large_carnivores
  target_task: large_omnivores_herbivores
  pair_group: main_strong_6
- pair_index: 6
  pair_id: p06_large_omnivores_herbivores_to_large_carnivores
  source_task: large_omnivores_herbivores
  target_task: large_carnivores
  pair_group: main_strong_6
